name: Node.js CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Definimos o Postgres como um serviço para os testes de integração
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: nest-clean-arch-test
        ports:
          - 5432:5432
        # Aguarda o postgres estar pronto antes de iniciar o job
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: 'npm install'

      - name: Generate Prisma Client
        run: npx prisma generate

      # Criamos os arquivos .env necessários para o dotenv-cli não falhar
      - name: Create .env files
        run: echo "DATABASE_URL=postgresql://postgres:docker@localhost:5432/nest-clean-arch-test" > .env.test

      - name: Run Prisma Migrations
        run: npx dotenv-cli -e .env.test -- npx prisma migrate deploy

      - name: Run Unit Tests
        run: npm run test

      - name: Run Integration Tests
        run: npm run test:int
